management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 1qazxsw2#
    driver-class-name: com.mysql.cj.jdbc.Driver


